---
# tasks file for roles/docker
- name: apt update
  become: true
  become_method: sudo
  apt:
    update_cache: yes

- name: Remove apt lock file
  file:
    state: absent
    path: "/var/lib/dpkg/lock"
    
- name: install Docker
  apt:
    name: docker.io
    state: present
- name: start Docker service
  service:
    name: docker
    state: started
    enabled: yes