---
# tasks file for roles/docker

- name: Wait for sudo
  become: yes
  shell: |
    while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do
      sleep 5
    done

- name: apt update
  become: yes
  apt:
    update_cache: yes

- name: install Docker
  become: yes
  apt:
    name: docker.io
    state: present

- name: start Docker service
  become: yes
  service:
    name: docker
    state: started
    enabled: yes