---
- name: Install and configure Docker on Ubuntu
  become: yes
  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: install Docker
      apt:
        name: docker.io
        state: present

    - name: start Docker service
      service:
        name: docker
        state: started
        enabled: yes