---
# tasks file for roles/docker
- name: apt update
  become: true
  become_method: sudo
  become_user: ubuntu
  apt:
    update_cache: yes
- name: install Docker
  apt:
    name: docker.io
    state: present
- name: start Docker service
  service:
    name: docker
    state: started
    enabled: yes